export const metadata = {
  title: "Terms & Conditions | Fiscal Forum",
  description: "Read the terms and conditions for using Fiscal Forum's financial services, research reports, and referral programs. Understand your rights and responsibilities.",
  keywords: [
    "terms and conditions",
    "Fiscal Forum terms",
    "financial services terms",
    "research reports terms",
    "referral program terms",
    "user agreement",
    "service terms India",
  ],
  authors: [{ name: "Fiscal Forum Team", url: "https://www.fiscalforum.in" }],
  creator: "Fiscal Forum",
  publisher: "Fiscal Forum",
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  openGraph: {
    title: "Terms & Conditions – Fiscal Forum",
    description: "Understand the terms and conditions for accessing Fiscal Forum's free financial services, research reports, and referral rewards.",
    url: "https://www.fiscalforum.in/terms-and-conditions",
    siteName: "Fiscal Forum",
    locale: "en_IN",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Terms & Conditions | Fiscal Forum",
    description: "Read Fiscal Forum's terms and conditions for financial services, reports, and referral programs.",
  },
};
