import React from "react";
import { Source_Serif_4 } from "next/font/google";
import { metadata } from "./metadata";
export { metadata };

export const dynamic = "force-dynamic";
export const revalidate = 0;

const sourceSerif = Source_Serif_4({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
  variable: "--font-source-serif",
});

export default function TermsAndConditionsPage() {
  return (
    <div
      className={`min-h-screen bg-[#F3EEE3] text-[#171512] pt-24 sm:pt-28 pb-16 font-sans selection:bg-[#2F4A3C] selection:text-white ${sourceSerif.variable}`}
    >
      {/* Header */}
      <div className="max-w-[850px] mx-auto px-6">
        <header className="border-b border-[#D9D0BC] py-5">
          <div className="flex justify-between items-baseline gap-4 flex-wrap">
            <div className="font-[family-name:var(--font-source-serif)] font-semibold text-lg tracking-[0.01em]">
              Fiscal Forum Finserv
            </div>
            <div className="text-xs text-[#4A453D]">
              Terms of Use
            </div>
          </div>
        </header>
      </div>

      {/* Hero Header */}
      <div className="max-w-[850px] mx-auto px-6">
        <section className="pt-12 pb-8 border-b border-[#D9D0BC]">
          <h1 className="font-[family-name:var(--font-source-serif)] font-bold text-[32px] sm:text-[40px] leading-[1.18] mb-4 text-[#171512] underline decoration-2 underline-offset-4">
            Terms &amp; Conditions
          </h1>
        </section>
      </div>

      {/* Content Body */}
      <div className="max-w-[850px] mx-auto px-6">
        <section className="py-10 space-y-6 text-[15px] sm:text-[15.5px] leading-[1.75] text-[#2C2825]">
          {/* Point 1 */}
          <div className="py-4 border-b border-[#D9D0BC]/60 flex gap-4 items-start">
            <span className="font-semibold text-[#171512] min-w-[24px]">1.</span>
            <p className="m-0">
              This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
            </p>
          </div>

          {/* Point 2 */}
          <div className="py-4 border-b border-[#D9D0BC]/60 flex gap-4 items-start">
            <span className="font-semibold text-[#171512] min-w-[24px]">2.</span>
            <p className="m-0">
              This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name{" "}
              <strong className="font-bold text-[#171512]">https://www.fiscalforum.in</strong> (&apos;Website&apos;), including the related mobile site and mobile application (hereinafter referred to as &apos;Platform&apos;).
            </p>
          </div>

          {/* Point 3 */}
          <div className="py-4 border-b border-[#D9D0BC]/60 flex gap-4 items-start">
            <span className="font-semibold text-[#171512] min-w-[24px]">3.</span>
            <p className="m-0">
              The Platform is owned by <strong className="font-bold text-[#171512]">8696060387</strong>, a company incorporated under the Companies Act, 1956 with its registered office at <strong className="font-bold text-[#171512]">A-581 Azad Nagar bhilwara</strong> (hereinafter referred to as &lsquo;Platform Owner&rsquo;, &lsquo;we&rsquo;, &lsquo;us&rsquo;, &lsquo;our&rsquo;)..
            </p>
          </div>

          {/* Point 4 */}
          <div className="py-4 border-b border-[#D9D0BC]/60 flex gap-4 items-start">
            <span className="font-semibold text-[#171512] min-w-[24px]">4.</span>
            <p className="m-0">
              Your use of the Platform and services and tools are governed by the following terms and conditions (&ldquo;Terms of Use&rdquo;) as applicable to the Platform including the applicable policies which are incorporated herein by way of reference. If You transact on the Platform, You shall be subject to the policies that are applicable to the Platform for such transaction. By mere use of the Platform, You shall be contracting with the Platform Owner and these terms and conditions including the policies constitute Your binding obligations, with Platform Owner. These Terms of Use relate to your use of our website, goods (as applicable) or services (as applicable) (collectively, &apos;Services&apos;). Any terms and conditions proposed by You which are in addition to or which conflict with these Terms of Use are expressly rejected by the Platform Owner and shall be of no force or effect. These Terms of Use can be modified at any time without assigning any reason. It is your responsibility to periodically review these Terms of Use to stay informed of updates..
            </p>
          </div>

          {/* Point 5 */}
          <div className="py-4 border-b border-[#D9D0BC]/60 flex gap-4 items-start">
            <span className="font-semibold text-[#171512] min-w-[24px]">5.</span>
            <p className="m-0">
              For the purpose of these Terms of Use, wherever the context so requires &lsquo;you&rsquo;, &lsquo;your&rsquo; or &lsquo;user&rsquo; shall mean any natural or legal person who has agreed to become a user/buyer on the Platform..
            </p>
          </div>

          {/* Point 6 */}
          <div className="py-5 px-5 bg-[#EAE2D2] border border-[#D9D0BC] rounded-md flex gap-4 items-start my-2">
            <span className="font-semibold text-[#171512] min-w-[24px]">6.</span>
            <p className="m-0 font-semibold text-[#171512] tracking-wide leading-[1.65]">
              ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING..
            </p>
          </div>

          {/* Point 7 */}
          <div className="py-5 border-b border-[#D9D0BC]/60">
            <div className="flex gap-4 items-start mb-4">
              <span className="font-semibold text-[#171512] min-w-[24px]">7.</span>
              <p className="m-0 font-medium text-[#171512]">
                The use of Platform and/or availing of our Services is subject to the following Terms of Use:
              </p>
            </div>

            <div className="pl-6 sm:pl-10 space-y-4">
              {[
                "To access and use the Services, you agree to provide true, accurate and complete information to us during and after registration, and you shall be responsible for all acts done through the use of your registered account on the Platform..",
                "Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials offered on this website or through the Services, for any specific purpose. You acknowledge that such information and materials may contain inaccuracies or errors and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law..",
                "Your use of our Services and the Platform is solely and entirely at your own risk and discretion for which we shall not be liable to you in any manner. You are required to independently assess and ensure that the Services meet your requirements..",
                "The contents of the Platform and the Services are proprietary to us and are licensed to us. You will not have any authority to claim any intellectual property rights, title, or interest in its contents. The contents includes and is not limited to the design, layout, look and graphics..",
                "You acknowledge that unauthorized use of the Platform and/or the Services may lead to action against you as per these Terms of Use and/or applicable laws..",
                "You agree to pay us the charges associated with availing the Services..",
                "You agree not to use the Platform and/ or Services for any purpose that is unlawful, illegal or forbidden by these Terms, or Indian or local laws that might apply to you.",
                "You agree and acknowledge that website and the Services may contain links to other third party websites. On accessing these links, you will be governed by the terms of use, privacy policy and such other policies of such third party websites. These links are provided for your convenience for provide further information..",
                "You understand that upon initiating a transaction for availing the Services you are entering into a legally binding and enforceable contract with the Platform Owner for the Services..",
              ].map((subItem, index) => (
                <div key={index} className="flex gap-3 items-start bg-[#FBF8F1] p-3.5 rounded border border-[#D9D0BC]/40">
                  <span className="font-semibold text-[#2F4A3C] min-w-[20px] text-sm">{index + 1}.</span>
                  <p className="m-0 text-[#2C2825] leading-[1.65] text-sm sm:text-[14.5px]">{subItem}</p>
                </div>
              ))}
            </div>
          </div>

          {/* Point 10 */}
          <div className="py-4 border-b border-[#D9D0BC]/60 flex gap-4 items-start">
            <span className="font-semibold text-[#171512] min-w-[24px]">10.</span>
            <p className="m-0">
              You shall indemnify and hold harmless Platform Owner, its affiliates, group companies (as applicable) and their respective officers, directors, agents, and employees, from any claim or demand, or actions including reasonable attorney&apos;s fees, made by any third party or penalty imposed due to or arising out of Your breach of this Terms of Use, privacy Policy and other Policies, or Your violation of any law, rules or regulations or the rights (including infringement of intellectual property rights) of a third party.
            </p>
          </div>

          {/* Point 11 */}
          <div className="py-4 border-b border-[#D9D0BC]/60 flex gap-4 items-start">
            <span className="font-semibold text-[#171512] min-w-[24px]">11.</span>
            <p className="m-0">
              Notwithstanding anything contained in these Terms of Use, the parties shall not be liable for any failure to perform an obligation under these Terms if performance is prevented or delayed by a force majeure event..
            </p>
          </div>

          {/* Point 12 */}
          <div className="py-4 border-b border-[#D9D0BC]/60 flex gap-4 items-start">
            <span className="font-semibold text-[#171512] min-w-[24px]">12.</span>
            <p className="m-0">
              These Terms and any dispute or claim relating to it, or its enforceability, shall be governed by and construed in accordance with the laws of India..
            </p>
          </div>

          {/* Point 13 */}
          <div className="py-4 border-b border-[#D9D0BC]/60 flex gap-4 items-start">
            <span className="font-semibold text-[#171512] min-w-[24px]">13.</span>
            <p className="m-0">
              All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in <strong className="font-bold text-[#171512]">Bhilwara</strong> and <strong className="font-bold text-[#171512]">Rajasthan</strong>.
            </p>
          </div>

          {/* Point 14 */}
          <div className="py-4 flex gap-4 items-start">
            <span className="font-semibold text-[#171512] min-w-[24px]">14.</span>
            <p className="m-0">
              All concerns or communications relating to these Terms must be communicated to us using the contact information provided on this website
            </p>
          </div>
        </section>
      </div>

      {/* Page Footer Note */}
      <div className="max-w-[850px] mx-auto px-6 mt-6">
        <footer className="border-t border-[#D9D0BC] py-6 text-xs text-[#4A453D] flex justify-between flex-wrap gap-2">
          <span>© Fiscal Forum Finserv</span>
          <span>Bhilwara, Rajasthan, India</span>
        </footer>
      </div>
    </div>
  );
}