import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { GlowCursor } from "./components/GlowCursor";
import Navbar from "./components/Navbar";
import Provider from "./provider";
import Footer from "./components/Footer";
import Hero from "./components/Hero";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className="scroll-smooth">
        <body
          className={'antialiased min-h-screen bg-gradient-to-br from-green-900 via-emerald-800 to-green-500 text-white'}
        >
          <GlowCursor />
          <Navbar/>
          <Hero/>
          <Provider>{children}</Provider>
          <Footer/>
        </body>
      </html>
    </ClerkProvider>
  );
}
